### PR TITLE
Change the error map in ts-openssl

### PR DESCRIPTION
**Pull request by yingxiongraomingzk**
Fix the error map in ts-openssl. Do not map SSL_ERROR_ZERO_RETURN with
ENOTCONN anymore.

### CODE REVIEW

**Comment by npmccallum** [comment]
Okay. Let's step back and look at the bigger picture.

The `o2e()` function is used to translate openssl errors into errno system errors. It is called by three functions: `tls_read()`, `tls_write()` and `tls_handshake()`. openssl returns an error `SSL_ERROR_ZERO_RETURN`. The question is how to perform this translation.

One thing isn't clear to me. When is `SSL_ERROR_ZERO_RETURN` returned? Does it indicate that no data was read and the connection is still open (condition A)? Or does it indicate that the connection is closed and no further communication is possible (condition B)?

`tls_read()` and `tls_write()` have the same error semantics as `read()` and `write()`, respectively. This means that both functions should return -1 and set `errno = EAGAIN` in condition A. In condition B they should return 0.

`tls_handshake()` should act like `tls_read()` and `tls_write()` in condition A. However, in condition B it should return -1 and set `errno = ENOTCONN`.

The current code, before your changes, presumes that the `tls_handshake()` condition B translation should be used in all cases. This is clearly not correct. But we still have to find out how to distinguish between these two conditions. The following link (a search through openssl for the error code) should help you:

https://github.com/openssl/openssl/search?q=SSL_ERROR_ZERO_RETURN&unscoped_q=SSL_ERROR_ZERO_RETURN

**Comment by yingxiongraomingzk** [comment]
I did some tests. I think SSL_ERROR_ZERO_RETURN is returned when serv receives a  normal close_nofity, which means no more writing in the client. In our program, if I use Ctrl+D to end a tls connection I receive SSL_ERROR_ZERO_RETURN, when I use Ctrl+C to terminate the connection I get SSL_ERROR_SYSCALL. So I think SSL_ERROR_ZERO_RETURN is not included in the handshake phase.

**Comment by npmccallum** [comment]
@yingxiongraomingzk Can you write tests?

First, write a test that has a normal TCP socket connection. The client should connect to the server. Then the server should disconnect. Then the client tries to read() and write(). What error numbers are returned?

Second, write the same test using TLS on openssl.

Third, write the same test using TLS on gnutls.

All three should have *exactly* the same behavior.

**Comment by yingxiongraomingzk** [comment]
@npmccallum Sure. I did the test manually. I will try both script and by hand this time.

**Comment by npmccallum** [comment]
@yingxiongraomingzk Just to be clear, by writing tests I mean make pull requests so that the tests can run in our automated test environment.

**Comment by yingxiongraomingzk** [comment]
@npmccallum Copy that.

**Comment by npmccallum** [comment]
@yingxiongraomingzk Don't update the readme. You can use markdown in comments in the pull request. GitHub lets you use markdown pretty much everywhere.

**Comment by yingxiongraomingzk** [comment]
@npmccallum It seems that Github does not support flowchart in markdown.
https://stackoverflow.com/questions/34836305/how-do-i-make-a-flowchart-using-markdown-on-my-github-blog
I know it is not good, but here I just post the chart in picture.
Chart

**Comment by npmccallum** [comment]
@yingxiongraomingzk Please don't use an existing pull request and branch for this. Make a new one. Branching and merging is cheap in git. So we almost always want to avoid reuse.

**Pull request closed without merging**
